package cn.edu.xmu.g12.g12ooadgoods.mapper;

import cn.edu.xmu.g12.g12ooadgoods.model.po.AuthUserProxyPo;
import cn.edu.xmu.g12.g12ooadgoods.model.po.AuthUserProxyPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuthUserProxyPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_proxy
     *
     * @mbg.generated
     */
    int deleteByExample(AuthUserProxyPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_proxy
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_proxy
     *
     * @mbg.generated
     */
    int insert(AuthUserProxyPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_proxy
     *
     * @mbg.generated
     */
    int insertSelective(AuthUserProxyPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_proxy
     *
     * @mbg.generated
     */
    List<AuthUserProxyPo> selectByExample(AuthUserProxyPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_proxy
     *
     * @mbg.generated
     */
    AuthUserProxyPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_proxy
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AuthUserProxyPo record, @Param("example") AuthUserProxyPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_proxy
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AuthUserProxyPo record, @Param("example") AuthUserProxyPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_proxy
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AuthUserProxyPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_proxy
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AuthUserProxyPo record);
}