package cn.edu.xmu.g12.g12ooadgoods.mapper;

import cn.edu.xmu.g12.g12ooadgoods.model.po.AuthPrivilegePo;
import cn.edu.xmu.g12.g12ooadgoods.model.po.AuthPrivilegePoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuthPrivilegePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_privilege
     *
     * @mbg.generated
     */
    int deleteByExample(AuthPrivilegePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_privilege
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_privilege
     *
     * @mbg.generated
     */
    int insert(AuthPrivilegePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_privilege
     *
     * @mbg.generated
     */
    int insertSelective(AuthPrivilegePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_privilege
     *
     * @mbg.generated
     */
    List<AuthPrivilegePo> selectByExample(AuthPrivilegePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_privilege
     *
     * @mbg.generated
     */
    AuthPrivilegePo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_privilege
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AuthPrivilegePo record, @Param("example") AuthPrivilegePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_privilege
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AuthPrivilegePo record, @Param("example") AuthPrivilegePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_privilege
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AuthPrivilegePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_privilege
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AuthPrivilegePo record);
}