package cn.edu.xmu.g12.g12ooadgoods.mapper;

import cn.edu.xmu.g12.g12ooadgoods.model.po.AuthUserRolePo;
import cn.edu.xmu.g12.g12ooadgoods.model.po.AuthUserRolePoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuthUserRolePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_role
     *
     * @mbg.generated
     */
    int deleteByExample(AuthUserRolePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_role
     *
     * @mbg.generated
     */
    int insert(AuthUserRolePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_role
     *
     * @mbg.generated
     */
    int insertSelective(AuthUserRolePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_role
     *
     * @mbg.generated
     */
    List<AuthUserRolePo> selectByExample(AuthUserRolePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_role
     *
     * @mbg.generated
     */
    AuthUserRolePo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AuthUserRolePo record, @Param("example") AuthUserRolePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AuthUserRolePo record, @Param("example") AuthUserRolePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AuthUserRolePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AuthUserRolePo record);
}