package cn.edu.xmu.g12.g12ooadgoods.mapper;

import cn.edu.xmu.g12.g12ooadgoods.model.po.CouponSkuPo;

public interface CouponSkuPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_sku
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_sku
     *
     * @mbg.generated
     */
    int insert(CouponSkuPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_sku
     *
     * @mbg.generated
     */
    int insertSelective(CouponSkuPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_sku
     *
     * @mbg.generated
     */
    CouponSkuPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_sku
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CouponSkuPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_sku
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CouponSkuPo record);
}