package cn.edu.xmu.g12.g12ooadgoods.mapper;

import cn.edu.xmu.g12.g12ooadgoods.model.po.FavouriteGoodsPo;

public interface FavouriteGoodsPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite_goods
     *
     * @mbg.generated
     */
    int insert(FavouriteGoodsPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite_goods
     *
     * @mbg.generated
     */
    int insertSelective(FavouriteGoodsPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite_goods
     *
     * @mbg.generated
     */
    FavouriteGoodsPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FavouriteGoodsPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FavouriteGoodsPo record);
}