package cn.edu.xmu.g12.g12ooadgoods.mapper;

import cn.edu.xmu.g12.g12ooadgoods.model.po.ShareActivityPo;

public interface ShareActivityPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_activity
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_activity
     *
     * @mbg.generated
     */
    int insert(ShareActivityPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_activity
     *
     * @mbg.generated
     */
    int insertSelective(ShareActivityPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_activity
     *
     * @mbg.generated
     */
    ShareActivityPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShareActivityPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShareActivityPo record);
}