package cn.edu.xmu.g12.g12ooadgoods.mapper;

import cn.edu.xmu.g12.g12ooadgoods.model.po.TimeSegmentPo;

public interface TimeSegmentPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_segment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_segment
     *
     * @mbg.generated
     */
    int insert(TimeSegmentPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_segment
     *
     * @mbg.generated
     */
    int insertSelective(TimeSegmentPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_segment
     *
     * @mbg.generated
     */
    TimeSegmentPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_segment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TimeSegmentPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_segment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TimeSegmentPo record);
}