
spring:
  boot:
    admin:
      client:
        url: http://172.16.1.156:8084
  datasource:
    url: jdbc:mysql://172.16.1.135:3306/oomall
    username: root
    password: 123
    druid:
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        enabled: true
        url-pattern: /druid/*
  redis:
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码
#    password: 123456
